export const EVENTS = {
  JOIN: "JOIN",
  JOINED: "JOINED",
  BROADCAST_MSG: "BROADCAST_MSG",
  CHECK: "CHECK",
  NEW_CHAT: "NEW_CHAT",
  CHECK_OLD_CHATS: "CHECK_OLD_CHATS",
  RECEIVE_OLD_CHATS: "RECEIVE_OLD_CHATS",
};
